#import "@preview/xyznote:0.3.0": *
#import "@preview/physica:0.9.4": * 
#import "@preview/cetz:0.3.2":
#import "@preview/fletcher:0.5.5": *
#import "@preview/alchemist:0.1.4"

= Introduction

We're going to concern ourselves with the general topic "light-matter"
interactions throughout these notes. This includes both the fundamental
quantum electrodynamical arguments, optical material properties, and details
of light scattering and propagation such as the theory of coherence. I
thought it'd be useful to chart the current knowledge contained in them, 
and how it's organized.



= Nonlinear Setting for materials
#linebreak()


Radiating solutions to Maxwell's equation lead to EM waves and the like.
Inside a material, light-matter interactions introduce generalized
multipole modes of the radiation field, generating the _macroscopic
electric field_ $bold(D) (bold(x), t)$, which is given, generally, as:

$ bold(D) = epsilon_0bold(E) + chi bold(P(E)) $

Where $chi bold(P(E))$ is the _polarization_ of the material as a function
of the external electric field, with an associated coupling constant $chi$
named the _electric susceptibility_. The effects of $bold(P)$ encode the material
properties of the medium, and can be computed
by first principles or numerical simulation on a case-to-case basis. For example,
some material like water may contain more polarization than pure glass because
of the fields produced by polar bonds.

The _idea_ behind nonlinear optics is actually quite simple; to some low
order of energy, the effects of this polarization
are very small and can, most of the time, be "averaged out" in such
a fashion as to add some constant multiples of the answers in a vacuum, which is
the _linear polarization_ $epsilon_0 chi^((1)) bold(E)$.
However, when we talk about really thrashing those waves around, violently, in
sensitive spaces and materials, on the order of 
$bold(E)_"waves" ~ bold(E)_"interactions"$, we can _access_ higher orders of 
perturbation of $bold(P)$.

In this we can think of three ways: _classically, semi-classically_ and
_quantum mechanically_. Therefore we may speak both of waves wiggling around
in a medium, but also of _photons_ being captured, emitted and modulated.
On the classical side, we may study the theory of anharmonic oscillators
to get all the major qualitative effects, semi-classically to get very good
approximations and all of the observed behavior, and purely quantum mechanically
with a path integral/field-theoretic approach.

There are four "major" regimes for nonlinear optics, *_parametric,
non-parametric, non-resonant and resonant_*. Parametric processes are the ones
that conserve the quantum state as to $braket(phi, u, phi)$, non-parametric
processes alter the quantum state as to $braket(phi_f, u, phi_i)$, and
resonant and non-resonant processes are distinguished by the closeness of
quanta frequencies to eigenmodes of the material, which introduce
divergences in certain approximations because of heightened energy.


== Orders of Polarization
https://royalsocietypublishing.org/doi/epdf/10.1098/rsta.2023.0339
If we imagine the potentials associated to materials are anharmonic (as they
actually are), the nonlinear behavior of radiation in matter can
be easily obtained if one can Taylor expand the inharmonicity present in $bold(P(E))$ as:

$
bold(P(E)) = sum^(infinity)_(n=0) 1/n! (grad^n bold(P)(0)) dot bold(E)^n 
$

Where $bold(A dot E)$ is a tensor contraction and 
$bold(E)^n = bold(E times.circle E times.circle dots )$.
The terms of the form $(n!epsilon_0)^(-1) grad^n bold(P)(0)$ are renamed
as $chi^n$, the _*tensor susceptibilities*_ or _couplings_ 
for every order of perturbation theory of the polarizing contribution. 
It is $chi^((n))$ that determines
how the polarization field will react in temporal and frequency domains,
_dampening, amplifying_ and overall _modifying_ the modes of radiation.
This yields:

$
bold(P(E)) = epsilon_0 bold(E) + bold(P(E)) = epsilon_0 ((1+chi^((1))) dot bold(E) + 
chi^((2)) : (bold(E times.circle E)) + dots)
$

One must note, this approximation only works in _non-resonant_ media,
as this series diverges whenever the material is highly energized 
by photons near their own energy eigenmodes (the potential becomes
highly deformed at a rate larger than the growth $~grad bold(P)$).
This is corrected by using direct atom-laser models.

This is rather intuitive when thinking about _*anharmonic potentials*_;
if we believe in a spring system with some coupling ("spring constant")
$kappa$, then the polarization is a displacement generated by
$kappa bold(E) = bold(P)$. For large displacements where the potential
ceases to be parabolic, and
where the coupling may be proportional to the displacement itself, the total
_induced_ displacement in such a way a polarization $P_x$ might
be generated by a force in some other direction $E_y$, generating
then a contribution $epsilon_0 chi_(x y z) E_x E_y$:

$
P = ("1st") + chi_(a b) E_a E^b + (dots)
$

#figure(
  image(
  "../images/anharmonic_pot1.svg",
  fit: "cover",
  width: 30%
  ),
  caption: [A simple anharmonic potential, 
  and the (dashed) local harmonic approximation],
)


The nonlinear optical regime is given to any terms beyond the first one.
It is clear $chi_(i j dots k)$ acts as a modulator of the _total impulse
response_ of the electric field, and now has the role of codifying material
properties. In tensor form, we see that for every order
$n$, we have a $n+1$ order tensor $chi$ for that order:

$
bold(P)_i = epsilon_0 
( sum_j chi_(i j)^((1)) bold(E)_j 
+ sum_(j, k) chi_(i j k)^((2)) bold(E)_j bold(E)_k
+ sum_(j, k, l) chi_(i j k l)^((3)) bold(E)_j bold(E)_k bold(E)_l
+ dots
)
$

The exact form and equations of $chi$ are very important, and will be
derived later.






The properties of $chi^((n))$ are inferred from group theoretical arguments.

== Susceptibility and Conductivity

Response function = susceptibility = 2nd derivative of free energy

$

$


$
bold(D)(bold(x), t) = epsilon.alt integral_bb(R) 
epsilon.alt(bold(x) - bold(x)', t-t') bold(E)(bold(x)', t') d^3 bold(x) d t'
$

#figure(
  image(
  "../images/response/response_cone.svg",
  fit: "cover",
  width: 60%
  ),
  caption: [The structure of the generalized response function
  of the displacement field $bold(D)$. In the past
  lightcone, one should consider all values of the
  electric field in some given spacetime volume as to
  weight the total contribution to $bold(D)$ in the
  response event $(bold(x),t)$. Two contributing events
  of the total integral, $(bold(x)', t')$ and 
  $(bold(x)'', t'')$, are shown. The total _span of time_
  that determines how far back is the response affected
  by is the _frequency dispersion_, whilst the total
  breadth of space that affects the response
  is the _spatial dispersion_.],
  placement: top,
)

$
&bold(J) = rho(bold(x)) dot(bold(x)) = sigma bold(E) \
&bold(P) = rho(bold(x)) bold(x) = epsilon_0 chi bold(E)
$


Denoted then by $sigma(q, omega)$ is the _*optical conductivity*_.
The relation between the susceptibility and conductivity of a material
is of a linear variation in $omega$ and quadratic variation in $q$

$
bold(J)(omega) = sigma(omega) bold(E)(omega)
$

This can be seen as the generalized AC conductivity, or the
inverse _Ohm's law_ for a general material



$
(q sigma)/omega = rho/(|bold(E)|), quad rho = chi phi.alt, quad |bold(E)| = -i q phi.alt  \
sigma(q, omega) = (i e^2 omega)/q^2 chi(q, omega)
$

https://link.springer.com/content/pdf/10.1007/978-3-662-02406-5.pdf
https://arxiv.org/pdf/2004.04561
https://arxiv.org/pdf/2401.09689
https://arxiv.org/pdf/1507.04947
https://arxiv.org/pdf/2409.03443
https://physics.stackexchange.com/questions/395583/why-is-two-photon-absorption-a-third-order-non-linear-process
https://thiscondensedlife.wordpress.com/2016/05/02/phase-difference-after-resonance/
https://arxiv.org/pdf/1612.09399
https://apps.dtic.mil/sti/tr/pdf/ADA164536.pdf

https://mpl.mpg.de/fileadmin/user_upload/Chekhova_Research_Group/Lecture_4_8.pdf
https://thiscondensedlife.wordpress.com/2017/07/27/response-and-dissipation-part-1-of-the-fluctuation-dissipation-theorem/

$
mat("Average"; "magnetization"; "for state" sigma) =
expectationvalue(m) = sum_i m_i and p_i 
$
https://physics.stackexchange.com/questions/174900/susceptibilities-and-response-functions
$
&expectationvalue(m) = -T (1/cal(Z) pdv(cal(Z), H)) = -T pdv(log[cal(Z)], H)= pdv(F, H) \
&pdv(F, H, 2) = expectationvalue(m^2) - expectationvalue(m_i)^2 = chi_M
$



== The symmetries of $chi^((n))$

One applies the _Neumann Principle_, which is just to constrain
the components of the response to some particular group 
$G$. The representation of such a group 
$M(a) : bb(R)^3 -> bb(R)^3, a in G$, we may define the
projection operator over the irrepresentations $K(a)$

$
P = 1/"size" sum_(a in G) K(a)
$

The eigenvalues of this operator, per crystallographic group,
will yield the associated allowed susceptibility tensor components.
In the case of $chi^((2))$, for example, all centrosymmetric
point groups, such as $(m m m, -1)$ and such have all zero eigenvalues.

@susceptibility_JatirianFoltides2016
@susceptibility_Popov2012
@susceptibility_Yang1995



=== The 32 Crystal Classes

=== Cubic Symmetry: $O_h$

=== Tetrahedral Symmetry: $T_d$

=== Hexagonal Symmetry: $D_(6h)$

=== Icosahedral Symmetry

=== Cubic Symmetry






== Incoming and outgoing modes

In most descriptions of nonlinear optics, one begins by assuming
the incoming field is a finite sum of monochromatic waves with
some amplitude $E_i$ and a polarization vector $bold(u)_alpha$
from some incoming direction $bold(r)$ in respect to the wavevector
$bold(k)$:

$
bold(E)(t) = E_i bold(u)_alpha exp(i omega_i t) exp(bold(k) dot bold(r))
$

There are some immediate difficulties. First, if we suppose
a very short pulse train (as is usual in atto/femtosecond physics), then
we aren't to describe the incoming field.

Some simple field

$
bold(E)(t) = E_i bold(u)_alpha exp(i omega_i t) exp(bold(k) dot bold(r))
$

The associated Fourier transform of this simple incoming mode is:

$
bold(E)(omega) = 
&undershell(
delta(omega - omega_a)E^(omega_a)_i +
delta(omega + omega_a)E^(omega_a)_i
, "Mode" omega_a "and its conjugate") \
+ space &undershell(
delta(omega - omega_b)E^(omega_b)_i +
delta(omega + omega_b)E^(omega_b)_i
, "Mode" omega_b "and its conjugate") \
$



Why

By means of the _optical theorem_,
there is a way of relating the order of optical perturbation to the number 
of field quanta that are interacting in any given process @optical_theorem1, 
namely that for an order $m$ we expect $m+1$ interacting fields.

=== Perturbation Theory for the anharmonic oscillator


$
a^(n)_m (t) = q¹(i hbar) sum_l integral_(-infinity)^t
d t' V_(m l)(t') a_l^(n-1)(t') exp(i omega_(m l) t')
$

$
expectationvalue(bold(p)) = braket(psi, bold(p), psi)
$

$
expectationvalue(bold(p)^((1))) 
= braket(psi^((0)), hat(bold(mu)), psi^((1)))
+ braket(psi^((1)), hat(bold(mu)), psi^((0)))
$

$
expectationvalue(bold(p)^((2))) 
= braket(psi^((0)), hat(bold(mu)), psi^((2)))
+ braket(psi^((2)), hat(bold(mu)), psi^((0)))
+ braket(psi^((1)), hat(bold(mu)), psi^((1)))
$

$
expectationvalue(bold(p)^((2))) 
= braket(psi^((0)), hat(bold(mu)), psi^((3)))
+ braket(psi^((3)), hat(bold(mu)), psi^((0)))
+ braket(psi^((1)), hat(bold(mu)), psi^((2)))
+ braket(psi^((2)), hat(bold(mu)), psi^((1)))
$


=== Diagrammatica

https://arxiv.org/pdf/1906.03197
Diagrammatic Schemes for Nonlinear Optical Interactions
https://publications.rwth-aachen.de/record/1005627/files/1005627.pdf
Diagrammatic Theory of Linear and Nonlinear Optics for Composite Systems
https://www.researchgate.net/publication/356836683_Diagrammatic_Theory_of_Linear_and_Nonlinear_Optics_for_Composite_Systems

Interpreting nonlinear vibrational spectroscopy with the classical mechanical analogs
of double-sided Feynman diagrams

https://ocw.mit.edu/courses/5-74-introductory-quantum-mechanics-ii-spring-2009/ba2bd7d6fb9c736aa6ef7f83541ea191_MIT5_74s09_lec14.pdf

==== Classical Feynman Diagrams

#import "@preview/cetz:0.2.2"

// Calculating and plotting wavelengths of the Lyman series
#let ns = (2, 3, 4, 5, 6, 1e12)
#let display(n) = if n == 1e12 { $infinity$ } else { str(n) }

// Using the Rydberg formula
#let wavelengths = ns.map(n => 1e9 / (1.097e7 * (1 - 1 / (n * n))))

#align(center)[
  #table(
    columns: (1fr,) * 6, align: center,
    // header row
    table.cell(colspan: 6)[Lyman Series Transition Wavelengths (nm)],
    // second row
    ..ns.map(n => [ n = #display(n) ]),
    // third row
    ..wavelengths.map(l => [ #calc.round(l, digits: 2) ])
  )

  #cetz.canvas({
    import cetz.draw: content
    import cetz.plot: *

    let opts = (
      size: (16, 3),
      axis-style: "scientific",
      x-label: $lambda "(nm)"$, y-label: none,
      x-tick-step: 2, y-tick-step: none,
      x-min: 86, x-max: 126,
    )
      
    plot(..opts, name: "plot", {
      for (l, n) in wavelengths.zip(ns) {
        // draw a vertical line
        add-vline(l, min: 0, max: 1, style: (stroke: black))
        // add anchors to "locate" the top of each vertical line
        add-anchor(str(n), (l, 1)) 
      }
    })
    for (l, n) in wavelengths.zip(ns) {
      // draw in the text labels at the anchors specified above
      content(
        "plot." + str(n),
        [n = #display(n)],
        anchor: "south-west",
        padding: 2pt,
        angle: 30deg
      )
    }
  })
]

==== $phi^4$ Interaction

mathstodon.xyz/ vacuumbubbles/111048295961622081
https://ash64.eu/assets/renormalization-article.pdf



























== The Limits of Nonlinearity

=== Energy Density 
First let's discuss the _observation_ of nonlinearity, rather than just
a generic initial description of its mathematical structure. 
The first thing is that nonlinear phenomena are _weak_, obviously so,
otherwise we'd regularly observe them. But why? As mentioned, it has
something to do with a ratio of the external electric field and the
interatomic energy present in the material. 

An estimate for the order
of the electric force in a hydrogen atom churns out to be of
some $10^(10) space V slash m$; a regular laser can only do as much
as $10^6 space V slash m$, meaning the atomic strength is some
4 orders of magnitude, or ten thousand times higher than the laser.
Pulsed GW capable lasers can reach some $10^8$, which makes effects
far more prominent. In fact, if any higher, nonlinearity
is superceded by ionization, the complete material breakdown. So we
operate on a "tight" regime.

Using the mental picture of the anharmonic oscillator with some
arbitrary polynomial potential $U(r)$, first order term would
be $U_0$. Now, the _energy density_ ought to be proportional
to:

$
mat("Stored energy"; "density") = Delta u_s ~u_0 prop N U_0
$

$
(Delta n)/n ~ 1/2 (Delta epsilon)/epsilon ~ (Delta u_s)/u_0
$

$
mat("Power"; "density") = I prop (Delta u_s)/tau
$

The true engineering effort is _*arbitrarily modifying the interaction
time $tau$ to produce nonlinear effects*_, and adjusting the bandwidth
limitations accordingly.





=== Optical Efficiency

We often
either associate the behavior of $chi^((n))$ or of atom-radiation coupled
systems to mean nonlinear, but as @limits_Khurgin_2023 points out, 
the observation of tangible nonlinear effects like frequency conversion
or intensity-dependent refraction are proportional to some degree of
_efficiency_ of the process. Note:

$
mat("Efficiency of"; "frequency conversion") = 
sin^2( omega/c (L)/(2n) chi^((m)) bold(E)^(m-1) )
$

Where $n$ is the index of refraction, $omega slash c = k_0$, and 
$L$ is the _length_ of the medium of propagation. Therefore the
observation of nonlinear effects is proportional to some minimal
effective length where the interaction has enough probability to occur
in the first place.

If we define the _nonlinear index change_ $Delta n$ is given by 
$(chi^((m)) bold(E)^(m-1) slash 2n)$, and the _nonlinear phase shift_
$Delta Phi_"nl"$ is $Delta n k_0 L$, then the previous efficiency
formula is now $sin^2(Delta Phi_"nl")$. This means that effective
nonlinear effects, of any order, like sum or difference generation,
four-wave mixing and the likes, require a $Delta Phi_"nl" >= pi$
to be maximally efficient.

As per @refraction_Neamtan1954, under the consideration of a simple
electromagnetic field and atomic vapor, the variation in the total
wavevector $bold(k)$ of incoming photons alters the total quantum 
state's $ket(psi)$ momenta by $Delta bold(p) = hbar bold(k)$, 
in such a way that the index of refraction is:

$
n = (|c hbar bold(k)|)/(|Delta W|) =
c mat("Change in"; "momentum") slash mat("Change in"; "energy")
$

Therefore, to isolate $Delta bold(p)$ we note how $Delta W$
ought to be proportional to $2pi hbar c f$:

$
|Delta bold(p)| &= (Delta n dot hbar |bold(k)| c) / (2pi hbar c f) \
&= Delta n hbar k_0 \
$

Now, since a change in the index of refraction is tantamount to a change
in momentum, by invoking the Uncertainty Principle, the interaction length 
$L$ must be such that the product $Delta p L >= hbar slash 2$, which
_then_ immediately postulates $Delta Phi_"nl" >= 1 slash 2$. That is,
the minimum length for nonlinear observation is a direct consequence of
Heisenberg's principle applied to some refractive medium.

This means that from a _practical_ point of view, $Delta Phi_"nl"$ *is
more important than* $chi^((n))$ for a given intensity of light.
As Khurgin puts it, it immediately explains why large nonlinearities
are observed at small scales; the minimal interaction length of materials
"boosts" their effective susceptibility $X$ by an enormous amount, but
actually scaling these effects to practical sizes is extremely complicated
because their actual efficiency is _vanishingly small_, as it is
directly proportional to both $L$ and $chi^((n))$.


=== Diagram Picture of Nonlinear Weakness





== The Precise Nature of $bold(P(E))$ <Polarization_section>


Polarization is a complicated phenomena, as it is an electric field
contribution both natural to atomic/molecular structures, and something
induced and amplified by external electric fields. _Polarization_
itself is the mean "dipole moment density" of a material:

$
bold(P) = (Delta bold(r)) / (Delta V) =
mat("Dipole moment";"per unit volume")
$


Which implies an atomistic view of dipoles as little floating things
that contribute to a total sum, as per the _Clausius-Mossotti model._
However, this model is insufficient to account for the real polarization
of the majority of materials since the quantum mechanical distribution
of dipoles is vastly more complicated. So we'll first investigate the 
ion-spring CM model, and then a modern view of polarization as 
an _adiabatic flow of current_.

$
Phi(bold(x)) = 1/(4pi epsilon_0) integral (d^3 x)/(|bold(x'-x)|)
(rho'(bold(x)) - div bold(P))
$

Therefore since $bold(E) = grad Phi$, the usual law 
$div bold(E) = rho$ holds as usual in the model.




=== The Clausius--Mossotti Model

The _Clausius-Mossotti_ or _Lorentz-Lorenz_ model is the simplest model of
polarization in dielectric media. If one pictures the millions of atoms
and molecules composing a material, they all may contain a small electric
dipole $bold(p)$. If by some kind of mechanism they come to be all 
partly arranged into one direction, the total polarization ought to be 
a mean, of their orientations and magnitudes @jackson1999classical. 
This is taken to be:

$
bold(P(x)) &= sum_i n_i expectationvalue(bold(p)_i) \
&= mat("Number of"; "dipoles")  mat("Mean of"; "little dipoles")
$

The origin of this little dipole moment $bold(p)$ is both naturally
from the atomic/molecular structure, but also _induced_ by an external
electric field acting upon the dielectric. If at first instance
$bold(P) = epsilon_0 chi_e bold(E)$, where $chi_e$ is the first order
electric susceptibility, in a densely packed array of ions the
external field $bold(E)$ induces a small internal field $bold(E)_i$,
so that the field of the ion is $bold(E) + bold(E)_i$.

Roughly, the covalent bonds and the atomic lattice sites need to be
"separated" in order for this idea to work, which is why the CM model
already falls flat at this stage, but let us proceed. The induced field
can be written as $bold(E)_i = bold(E)_"near" - bold(E_P)$, where
the near-field is from the atoms themselves, and $bold(E_P)$ is the
"ambient" electric field produced _en masse_ by the rest of the medium.

The mean field inside some extremely small sphere $S$ centered
around the atom would have an electric field:

$
bold(E)_i &= bold(E)_"near" - (3/(4pi R^3) integral_(r < R)
bold(E) space d^3 bold(x)) \
&= bold(E)_"near" + bold(P)/(3 epsilon_0)
$

Since $bold(P) prop n$





$
bold(P) = (n q^2)/m sum_i f_i/( (omega_0 - omega)^2 - i gamma_i omega) bold(E)(t)
$

=== Classical anharmonic potential

Specific heat, Energy Fluctuation and Entropy
of Isotropic Harmonic and Anharmonic Oscillators
https://ejs.journals.ekb.eg/article_151731_c4f574d42a1067c0f5cd62bb388b562f.pdf

We can produce a simple cubic anharmonic Hamiltonian $H$, and then
decomposing it into a free $H_0$ and a perturbing term $gamma x^3$
$
H = K +  1/2 k x^2 + gamma x^3  = H_0 + gamma x^3
$

The first order energy amplitude is

$
E_n^1 &= braket(0, gamma x^3, n) \
&= braket("even/odd ", " odd " , " even/odd") \
&= 0
$

$
E^2_0 = sum_(k != 0) ( |braket(0, gamma x^3, k)|^2)/(E_0^0 - E_k^0)
$

$
E_0 = E_0 + E_1 + E_2 = (hbar omega)/ 2 + 0 + 
$


=== Maxwell-Liouville approach

As per @Lucarini2005, still taking the simple idea 
$bold(P) = Delta bold(r) slash Delta V $, we may still talk
about the average polarization of millions of dipoles, but quantum
mechanically. 

$
i hbar partial_t rho (t) &= [H, rho(t)] \
&= [H_0, rho(t)] + [H^t_l, rho(t)] \
$

The principle here is that rather than expanding the series of
the polarization itself, we'll expand the density matrix as a
perturbed series, and then make an equivalence between the
regular susceptibility tensor at order $n$ to the density
matrix at order $n$, which may not be immediately intuitive.

$
rho(t)
$

$
bold(P)(t) = sum^infinity_(i = 1) P^((i))(t) =
sum^infinity_(i = 1) 1/V space Tr( sum_j -q bold(r)_j rho^((j))(t) )
$

Note that the validity of the perturbative approach is related to the as-
sumption that the absolute value of an oscillating electric field affecting elec-
trons is much smaller than a characteristic static electric field due to inter-
actions with the nucleus and with other electrons.

=== Resta's approach


https://www.vasp.at/wiki/index.php/Berry_phases_and_finite_electric_fields#cite_note-Vogl78-1

$
Delta bold(P) = 1/Omega_0 integral_(Omega_0) bold(r) delta(bold(r)) d^3 r
$

$
pdv(bold(P)_e, lambda) = (i |e| hbar)/(N Omega_0 m_e)
sum_bold(k) sum^M_(n = 1) sum^infinity_(m = M+1)

(braket(psi^((lambda))_(n k), bold(hat(p)),psi^((lambda))_(m k)) 
braket(psi^((lambda))_(m k),pdv(V^((lambda)),lambda),psi^((lambda))_(n k))
)/(
(epsilon.alt^((lambda))_(n bold(k)) - epsilon.alt^((lambda))_(m bold(k)))^2
) + "c.c"
$


=== Bulk--Boundary Correspondence


$
ket(v_n) = a integral_([-pi, pi]) (d bold(k)) / (2 pi) exp(-i k R_m) ket(psi_(n k))
$

$
bold(P) = -q a sum_(n in cal(O)) gamma_n / (2 pi)
$

$
Delta bold(P(k)) = -q a integral.cont (d bold(k))/(2 pi) dot bold(A(k))


$



=== Insulator localization

Polarization and localization in insulators: Generating function approach
Symmetry Analysis of the Non-Hermitian Electro-Optic Effect in Crystals


=== Polarization Tensors in a general setting

https://iopscience.iop.org/article/10.1088/1742-6596/12/1/002/pdf
https://arxiv.org/pdf/2105.08228
https://arxiv.org/pdf/2401.04180






A linear material has energy density:

$
U = 1/(8pi) bold(D dot E)
$

For a nonlinear material, we have to expand the contraction to all orders
of perturbation in such a way that we simply contract the conjugate field along:


$
U_i = 
&1/2 sum_(j, a) chi_(i j)^((1)) bold(E)^*_i (omega_a) bold(E)_j \

+ &1/3 sum_(j, k, \ a, b) chi_(i j k)^((2)) bold(E)^*_i (omega_a, omega_b) bold(E)_j bold(E)_k \

+ &1/4 sum_(j, k, l, \ a, b, c) chi_(i j k l)^((3)) bold(E)^*_i
(omega_a, omega_b, omega_c) bold(E)_j bold(E)_k bold(E)_l
+ dots
$

$
cal(H) = integral bold(H) dot d bold(H) + bold(E) dot d bold(E)
$

If $bold(D)(bold(x),t) = epsilon_0 bold(E) + chi bold(P(E))$

$
pdv((Pi_(i in I_n) E_i),E_k) 
&= sum_(j in I_n) pdv(E_j, E_k) product_(i != j) E_i \
&= sum_(j in I_n) delta_(j k) product_(i != j) E_i \
&= n product_(i in I_(n - 1)) E_i
$

Therefore
https://physics.stackexchange.com/questions/498693/derivation-of-hamiltonian-in-non-linear-optics

$
((d bold(P)^((n)))/(d bold(E)))_(i j) = n chi^((n))_(i j k_1 dots k_(n-1))
product_(i in I_(n - 2)) E_i
$




== A quantum argument for nonlinearity

In a quantum setting, we may justify the same. Imagine some simple two-state 
atomic system $H$; if in order to transition this from the state $A$ to
the state $B$ or vice-versa one requires quanta on the order of $hbar omega$,
it's not unreasonable to claim any


the transition probability  $abs(braket(B_"final",u,A_"initial"))^2$
under the influence of an electric field $bold(E)$ is:

$ Gamma = mat("Total transition";"probability") &approx 
( 1/hbar integral_(Delta t) H_(B A)(t) exp(i omega_(B A) t) d t )^2 \
&approx t^2/hbar^2 (e^2|bold(E)|^2)/(4m^2) 
abs(braket(B,epsilon dot exp(i k dot bold(r)),A))^2 sin^2((Delta omega) / 2) \
&approx t^2/hbar^2 e^2/(2m^2) (1/2 |bold(E)|^2) ("Amplitude")
$

Therefore the probability is directly proportional to the system's effective
mass and its incoming energy density in the form on an electromagnetic wave.
If the probability is in the order of $tilde Order(Gamma^2)$, then
simple argument is then that only at high field intensities, low-masses,
or high charge environments one expects to see these effects.

= The nonlinear wave equation
#linebreak()

From Maxwell's equation we can extract the general wave equation for electromagnetic
waves. The difficulty is that as the medium's polarization tensor and constitutive
equations get more complicated, so does the associated nonlinear wave equation describing
radiation inside of them.

Suppose that rather than in the pure vacuum, where $partial_t^2 bold(E)= c^2 grad^2bold(E)$,
we introduce that $bold(D) approx bold(E) + epsilon_0 chi bold(E)$, that is, a
_linearly polarized_ medium. Then it introduces a index of refraction $n$ associated
to a variation in light's local speed, directly proportional to the electric susceptibility. Notice $n = sqrt(Re(1+chi))$:

$
n^2 pdv(bold(E),t, 2) = c^2 grad^2 bold(E), quad n = sqrt(1+chi) >= 1
$

If we introduce a simple polarization tensor of the order of $(times.circle ^n bold(E))$
like before, then since $bold(P(E))$ has no obvious dependence, what is usual is to attempt
a decomposition $bold(P) ~ bold(P)_"linear" + bold(P)_"non-linear"$, abbreviated
as $bold(P)^1 + bold(P)^"nl"$. This produces:

$
-grad^2 bold(E) + grad(div bold(E)) + (epsilon bold(P)^1) / c^2 pdv(bold(E), t, 2) = 
- 1/(epsilon_0 c^2) pdv(bold(P)^"nl", t, 2)
$

== Variation of electric susceptibility
#linebreak()

Matter doesn't instantaneously react with light. A time delay effect for the acceleration
of internal charges by incoming radiation can be done with a _Lorentz_ model. Consider
the polarization vector $bold(P)(bold(x), t)$, it may be:

$
bold(P)(bold(x), t) = epsilon_0 integral_(-infinity)^t chi(t-t') bold(E)(bold(x), t') d t'
$

That is, at any given point $bold(x)$ and time $t$, the total polarization
vector is proportional to the _variation_ in some time interval $Delta t$, and the
electric field at $t'$. A Fourier transform reveals then that the electric susceptibility
actually _depends on the incoming frequency_ $tau$:

$
bold(P)_"freq" (bold(x), tau) = epsilon_0 chi_"freq" (tau) bold(E)_"freq" (bold(x), tau)
$

consider

== Light polarization

$
J(bold(x), t) = mat(bold(E)_x ; bold(E)_y e^(i theta))
exp(-i(omega t - k z))
$



== Ordinary and extraordinary polarizations

https://physics.stackexchange.com/questions/819851/extraordinary-polarization-in-a-birefringent-optical-medium

https://support.zemax.com/hc/en-us/articles/1500005486841-How-to-design-birefringent-polarizers

== Optical Theorem

$
2 Im(K(a -> b)) = sum_i integral d Pi_i K^dagger (b -> i)
K(a -> i)
$

http://fma.if.usp.br/~burdman/QFT1/lecture_26.pdf
https://arxiv.org/pdf/1205.3672

== Coherence Theory

Coherence theory is, generally, a method to make an accurate
_statistical_ and _information theoretic view_ of the electromagnetic field,
comprehending fundamental theorems about detectors and sources and their
limitations. The theory is only concerned with _measurable quantities_


Indeed, it seems all theories should be structured this way from
an operational perspective @perina1972coherence, both since experimentally
all quantities are captured with faulty equipment, but also because it
is _in principle_ impossible to formulate a quantum theory without noisy
detectors, but more on that in the QED section.

_Partial coherence_ is of utmost importance

The content of the theory is founded on the _generalized correlation_
function between a complexified, scalar component of the EM field and its
conjugate, which allows a bridge between it and quantum theory.


_Coherence_, from the perspective of signal processing, shows the degree that two 
_ergodic signals_ are related through a linear process 
(non-linearities and additional noise sources will decrease coherence). 
It is a real quantity with values between 0 and 1 (where 1 means one signal can be
completely established from the other through a linear filter). It is found by the 
ratio of the cross power spectral density divided by the individual power spectral 
densities as:


$
mat("Coherence of"; "two signals") = (|S_(x y)(t)|^2)/(S_(x x)(t) S_(y y)(t))
= mat("Cross power"; "spectral density"; "between" x "and" y)
slash.big mat("Power spectral"; "density of" x) mat("Power spectral"; "density of" y)
$

 That is exactly what coherence is, the degree that this holds, and it simply means that there is a least squared solution to make a filter such that we can recover x(t) from y(t) alone (so coherence gives us a measure of how effective a linear equalizer can be). 

$
Gamma^((m, n))_(mu_1 dots mu_(m+n))(bold(x_1), dots ,bold(x_(n+m)); t_1, dots, t_(n+m))
&= lr(angle.l product_(j = 1)^m V_(mu j)^*(bold(x)_j, t_j)
product^(m+n)_(k = m+1) V_(mu k)(bold(x)_k, t_k)
angle.r)
$

$
gamma^((n,n))(bold(x)_1, dots, bold(x)_(2n)) = 
(Gamma^((n, n))(bold(x_1), dots ,bold(x_(2n)); t_1, dots, t_(2n)))/
((product_(j=1)^(2n) Gamma^((n,n)) (bold(x)_j, dots, bold(x)_j)  )^(1/2))
$

$
 gamma^((n,n))_"Glaubner" (bold(x)_1, dots, bold(x)_(2n)) = 
(Gamma^((n, n))(bold(x_1), dots ,bold(x_(2n)); t_1, dots, t_(2n)))/
((product_(j=1)^(2n) Gamma^((1,1)) (bold(x)_j, bold(x)_j)  )^(1/2))
$

$
gamma^((n,n))_"Sudarshan" (bold(x)_1, dots, bold(x)_(2n)) = 
(Gamma^((n, n))(bold(x_1), dots ,bold(x_(2n)); t_1, dots, t_(2n)))/
(Gamma^((n, n))(bold(x_1), dots ,bold(x_n), bold(x_n), dots, bold(x_1))
Gamma^((n, n))(bold(x_(n+1)), dots ,bold(x_(2n)), bold(x_(2n)), dots, bold(x_(n+1))
)
$

$
(grad^2_i + kappa^2) cal(K)_(j m) = 0
$


https://hal.science/hal-04229183/document

=== Entropy of Light Beams

Suppose we're given the mutual intensity $J(bold(x)_1, bold(x)_2)$ of two
points. By expressing it as a scalar product of terms in a Hilbert space
$cal(H)$, using operator algebra, it can be decomposed into a diagonal matrix
with elements $lambda_n$:

$
J(bold(x)_1, bold(x)_2) = sum^(infinity)_(n = -infinity) lambda_n psi_n^*(x_1)
psi_n (x_2)
$

This can be interpreted as the incoherent superposition of elementary
light beams. The _probability_ $p_n$ of a photon to belong in the
$n$-th beam is given by the sum of elements $lambda_n$, normalized:

$
p_n = lambda_n/(sum_n lambda_n), quad sum_n p_n = 1, quad  lambda_n >= 0
$

So the total _entropy_ of this superposition of incoherent beams
may be just the total Shannon entropy, which is the mean of
$ln(1 slash p_n) = - ln p_n$:

$
H = - sum_n p_n ln p_n
$

Indeed, this functional is minimized when $lambda_i = 0$, which
represents a coherent, and "ordered", very self-correlated optical
field, whilst a maximally entropic field is given when $lambda = 1/N$


=== The Geometric Theory of Coherence

$
I =  gamma_(i j) u^i u^j
$

$
I_"coherent" = ( sum^n_i u^i )^2
$

$
I_"incoherent" = sum^n_i (u^i)^2, quad R^i_(j l m) = 0
$

$
R_(i j) - 1/2 gamma_(i j)R = chi T_(i j)
$

$
u^i' = u^i + xi^i (u) delta t
$

$
delta_L gamma_(i j) = 0, "Petrov"
$

$Delta I ~$ "movement in" $gamma_(i j)$

QUESTIONS: What if $gamma_(i j)$ is periodic/closed/bounded, what is
the metric for some interference fringe, can one perform the opposite
path of choosing a metric and then obtaining an optical experiment, or is it
constrained by some gauge freedom?

=== Coherency Matrix

We can formulate a simple frequency-space theory of light that also takes
into account its polarization. Wiener developed the so-called 
_coherency matrix_


$
cal(R) = 1/2 sum^3_(i = 0) s_i bold(sigma)_i ~ bb(H)
$

$
cal(J)(t) &= expectationvalue(cal(E)^* (t) plus.circle cal(E)(t+ tau)) \
&= mat(J_(x x), J_(x y) ; J_(y x), J_(y y))
$
 

#figure(
  image(
  "../images/coher_matrix_1.svg",
  fit: "cover",
  width: 100%
  ),
  caption: [The _spectral coherent matrix_ description of a light experiment.],
)

#figure(
  image(
  "../images/coher_matrix_2.svg",
  fit: "cover",
  width: 100%
  ),
  caption: [A compensator followed by a polarizer in the _spectral coherent
matrix_ description of light.],
)